version: '3.9'

services:
  #MongoDB service

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - '6000:27017'
    volumes:
      - mongo:/data/db

  # Node API service

  app:
    build: .
    ports:
      - '6006:6666'
    environment:
      PORT: 6666
      DATABASE: mongodb://mongo:27017/eventManagement
    depends_on:
      - mongo

volumes:
  mongo: {}
